language: generic
sudo: false
script:
  - openssl aes-256-cbc -k "$KEY_PASS" -in key.enc -out key -d
  - ssh-add key
  - git remote add prod ssh://jande112@unix11.csc.calpoly.edu/home/www/CPE-123
  - git push prod master
branches:
  only:
    - master
