language: generic
sudo: false
script:
  - openssl aes-256-cbc -k "$KEY_PASS" -in key.enc -out ~/key -d
  - chmod 600 ~/key
  - eval "$(ssh-agent -s)"
  - ssh-add ~/key
  - cat known_hosts >> ~/.ssh/known_hosts
  - git remote add prod ssh://jande112@unix11.csc.calpoly.edu/home/jande112/www/CPE-123
  - git push prod master
branches:
  only:
    - master
